---
- name: source
  include_tasks: "source:/{{ nginx_rtmp_module_source }}/main.yml"
  when: nginx_rtmp_module_source != "default"

- name: source default
  include_tasks: "pkg.yml"
  when: nginx_rtmp_module_source == "default"